#if os(macOS)
    import Foundation
    import Testing

    @testable import ClipboardCore

    /// Scriptable pasteboard double. Thread-safe because `readPayload()` is
    /// called from a detached task while the test mutates state from the
    /// main actor.
    final class FakePasteboard: PasteboardReading, @unchecked Sendable {
        private let lock = NSLock()
        private var changeCount = 0
        private var types: Set<String> = []
        private var payload: PasteboardCapture.Payload?
        private(set) var readCalls = 0
        private(set) var readSawMainThread: Bool?
        /// Simulates the pasteboard-privacy "Ask" stall.
        var readDelay: TimeInterval = 0

        func currentChangeCount() -> Int {
            lock.withLock { changeCount }
        }

        func currentTypes() -> Set<String> {
            lock.withLock { types }
        }

        func readPayload() -> PasteboardCapture.Payload? {
            let delay = lock.withLock {
                readCalls += 1
                readSawMainThread = Thread.isMainThread
                return readDelay
            }
            if delay > 0 { Thread.sleep(forTimeInterval: delay) }
            return lock.withLock { payload }
        }

        /// A new write lands: bump the count and replace content atomically.
        func write(_ newPayload: PasteboardCapture.Payload?, types newTypes: Set<String>) {
            lock.withLock {
                changeCount += 1
                payload = newPayload
                types = newTypes
            }
        }
    }

    /// Scriptable activity source for mode-transition turns.
    final class FakeActivity: UserActivitySource, @unchecked Sendable {
        private let lock = NSLock()
        private var secondsSinceInput: TimeInterval = 0
        private var locked = false

        func secondsSinceLastUserInput() -> TimeInterval {
            lock.withLock { secondsSinceInput }
        }

        func isScreenLocked() -> Bool {
            lock.withLock { locked }
        }

        func set(secondsSinceInput: TimeInterval = 0, locked: Bool = false) {
            lock.withLock {
                self.secondsSinceInput = secondsSinceInput
                self.locked = locked
            }
        }
    }

    @MainActor
    private func makeMonitor(
        pasteboard: FakePasteboard, activity: FakeActivity = FakeActivity()
    ) -> MacPasteboardMonitor {
        MacPasteboardMonitor(reader: pasteboard, activity: activity)
    }

    /// Drives poll turns until a capture arrives (or the attempt budget runs
    /// out — coalesced reads need a few turns to surface).
    @MainActor
    private func waitForCaptures(
        _ monitor: MacPasteboardMonitor, into captures: () -> [PasteboardCapture],
        count: Int = 1, attempts: Int = 200
    ) async {
        for _ in 0..<attempts where captures().count < count {
            try? await Task.sleep(for: .milliseconds(10))
        }
    }

    @Suite("MacPasteboardMonitor — capture pipeline")
    @MainActor
    struct MacPasteboardMonitorTests {

        @Test("A pasteboard change delivers a text capture")
        func capturesText() async {
            let pasteboard = FakePasteboard()
            let monitor = makeMonitor(pasteboard: pasteboard)
            var captures: [PasteboardCapture] = []
            monitor.onCapture = { captures.append($0) }

            pasteboard.write(.text("hello"), types: ["public.utf8-plain-text"])
            monitor.pollOnce()
            await waitForCaptures(monitor) { captures }

            #expect(captures.map(\.textRepresentation) == ["hello"])
        }

        @Test("Unchanged changeCount never reads")
        func noChangeNoRead() async {
            let pasteboard = FakePasteboard()
            let monitor = makeMonitor(pasteboard: pasteboard)
            monitor.onCapture = { _ in }

            monitor.pollOnce()
            monitor.pollOnce()
            try? await Task.sleep(for: .milliseconds(50))

            #expect(pasteboard.readCalls == 0)
        }

        @Test(
            "Sensitive types veto capture BEFORE any content read",
            arguments: [
                SensitivePasteboardTypes.concealed,
                SensitivePasteboardTypes.transient,
                SensitivePasteboardTypes.autoGenerated,
            ])
        func sensitiveVetoBeforeRead(vetoType: String) async {
            let pasteboard = FakePasteboard()
            let monitor = makeMonitor(pasteboard: pasteboard)
            var captures: [PasteboardCapture] = []
            monitor.onCapture = { captures.append($0) }

            pasteboard.write(.text("hunter2"), types: ["public.utf8-plain-text", vetoType])
            monitor.pollOnce()
            try? await Task.sleep(for: .milliseconds(100))

            #expect(captures.isEmpty)
            #expect(pasteboard.readCalls == 0, "veto must run before the read")
        }

        @Test("Our own self-write marker is never re-captured")
        func selfWriteSkipped() async {
            let pasteboard = FakePasteboard()
            let monitor = makeMonitor(pasteboard: pasteboard)
            var captures: [PasteboardCapture] = []
            monitor.onCapture = { captures.append($0) }

            pasteboard.write(
                .text("from gancho"),
                types: [
                    "public.utf8-plain-text",
                    MacPasteboardMonitor.selfWriteMarker.rawValue,
                ])
            monitor.pollOnce()
            try? await Task.sleep(for: .milliseconds(100))

            #expect(captures.isEmpty)
            #expect(pasteboard.readCalls == 0)
        }

        @Test("Universal Clipboard items carry the badge instead of a veto")
        func remoteClipboardBadge() async {
            let pasteboard = FakePasteboard()
            let monitor = makeMonitor(pasteboard: pasteboard)
            var captures: [PasteboardCapture] = []
            monitor.onCapture = { captures.append($0) }

            pasteboard.write(
                .text("from the iPhone"),
                types: [
                    "public.utf8-plain-text",
                    SensitivePasteboardTypes.remoteClipboard,
                ])
            monitor.pollOnce()
            await waitForCaptures(monitor) { captures }

            #expect(captures.count == 1)
            #expect(captures.first?.isFromUniversalClipboard == true)
        }

        @Test(
            "Rich payloads come through unchanged",
            arguments: [
                PasteboardCapture.Payload.image(
                    data: Data([1, 2, 3]), typeIdentifier: "public.png"),
                .richText(rtf: Data([0x7B]), plainText: "rich"),
                .html(source: "<b>hi</b>", plainText: "hi"),
                .fileReferences([URL(fileURLWithPath: "/tmp/a.txt")]),
            ])
        func richPayloads(payload: PasteboardCapture.Payload) async {
            let pasteboard = FakePasteboard()
            let monitor = makeMonitor(pasteboard: pasteboard)
            var captures: [PasteboardCapture] = []
            monitor.onCapture = { captures.append($0) }

            pasteboard.write(payload, types: ["anything"])
            monitor.pollOnce()
            await waitForCaptures(monitor) { captures }

            #expect(captures.map(\.payload) == [payload])
        }

        @Test("The content read never runs on the main thread")
        func readRunsOffMain() async {
            let pasteboard = FakePasteboard()
            let monitor = makeMonitor(pasteboard: pasteboard)
            var captures: [PasteboardCapture] = []
            monitor.onCapture = { captures.append($0) }

            pasteboard.write(.text("x"), types: ["public.utf8-plain-text"])
            monitor.pollOnce()
            await waitForCaptures(monitor) { captures }

            #expect(pasteboard.readSawMainThread == false)
        }

        @Test("A slow (Ask-stalled) read does not block the main actor")
        func slowReadKeepsMainResponsive() async {
            let pasteboard = FakePasteboard()
            // A long read so a real "blocked" main actor (the full read) is
            // unmistakably distinct from the actor merely being slow to resume
            // the hop below under a contended CI runner. Coverage-instrumented
            // CI VMs were seen taking ~2s just to resume the hop, so the read
            // sleeps well past that and the ceiling sits in the wide gap
            // between scheduler jitter and a genuine block.
            pasteboard.readDelay = 8.0
            let monitor = makeMonitor(pasteboard: pasteboard)
            var captures: [PasteboardCapture] = []
            monitor.onCapture = { captures.append($0) }

            pasteboard.write(.text("slow"), types: ["public.utf8-plain-text"])
            let before = ContinuousClock.now
            monitor.pollOnce()
            // If the read ran on the main actor, this hop would wait the full
            // 8s read. The ceiling absorbs the ~2s of scheduler jitter seen on
            // loaded CI coverage VMs while staying far below the 8s a genuine
            // block would cost.
            await Task.yield()
            let elapsed = ContinuousClock.now - before
            #expect(elapsed < .seconds(4))

            await waitForCaptures(monitor, into: { captures }, attempts: 1000)
            #expect(captures.count == 1)
        }

        @Test("A burst of changes coalesces to the latest content")
        func burstCoalesces() async {
            let pasteboard = FakePasteboard()
            pasteboard.readDelay = 0.2
            let monitor = makeMonitor(pasteboard: pasteboard)
            var captures: [PasteboardCapture] = []
            monitor.onCapture = { captures.append($0) }

            pasteboard.write(.text("first"), types: ["public.utf8-plain-text"])
            monitor.pollOnce()
            pasteboard.write(.text("second"), types: ["public.utf8-plain-text"])
            monitor.pollOnce()

            await waitForCaptures(monitor) { captures }
            try? await Task.sleep(for: .milliseconds(300))

            #expect(captures.map(\.textRepresentation) == ["second"])
        }

        @Test("Paused mode skips polling entirely; unlock resumes capture")
        func pausedSkipsPolling() async {
            let pasteboard = FakePasteboard()
            let activity = FakeActivity()
            let monitor = makeMonitor(pasteboard: pasteboard, activity: activity)
            var captures: [PasteboardCapture] = []
            monitor.onCapture = { captures.append($0) }

            activity.set(locked: true)
            pasteboard.write(.text("while locked"), types: ["public.utf8-plain-text"])
            _ = monitor.tick()
            try? await Task.sleep(for: .milliseconds(50))
            #expect(captures.isEmpty)
            #expect(pasteboard.readCalls == 0)

            // Locked-screen copies are discarded by privacy policy
            // (ProductionMonitorTests covers it); a fresh copy after unlock
            // captures normally.
            activity.set(locked: false)
            _ = monitor.tick()
            pasteboard.write(.text("after unlock"), types: ["public.utf8-plain-text"])
            _ = monitor.tick()
            await waitForCaptures(monitor) { captures }
            #expect(captures.map(\.textRepresentation) == ["after unlock"])
        }

        @Test("Sustained churn neither drops deliveries nor accumulates state")
        func sustainedChurn() async {
            let pasteboard = FakePasteboard()
            let monitor = makeMonitor(pasteboard: pasteboard)
            var captures: [PasteboardCapture] = []
            monitor.onCapture = { captures.append($0) }

            for round in 0..<500 {
                pasteboard.write(.text("clip \(round)"), types: ["public.utf8-plain-text"])
                monitor.pollOnce()
                await waitForCaptures(monitor, into: { captures }, count: round + 1)
                #expect(captures.last?.textRepresentation == "clip \(round)")
            }
            #expect(captures.count == 500)
            #expect(pasteboard.readCalls == 500)
        }
    }
#endif
