#if os(macOS)
    import Foundation
    import Testing

    @testable import ClipboardCore

    @MainActor
    private func makeMonitor(
        pasteboard: FakePasteboard,
        denylist: SourceAppDenylist = SourceAppDenylist(),
        frontmost: String? = nil
    ) -> MacPasteboardMonitor {
        let monitor = MacPasteboardMonitor(
            reader: pasteboard, activity: FakeActivity(),
            frontmostApp: { frontmost })
        monitor.denylist = denylist
        return monitor
    }

    @Suite("Sensitive-content guardrails")
    @MainActor
    struct SensitiveContentTests {

        /// The exact pasteboard shapes the big password managers write:
        /// all of them carry `org.nspasteboard.ConcealedType` (the
        /// nspasteboard.org convention they implement).
        @Test(
            "Password-manager copies are never stored",
            arguments: [
                ("1Password", ["public.utf8-plain-text", "org.nspasteboard.ConcealedType"]),
                (
                    "Bitwarden",
                    [
                        "public.utf8-plain-text", "org.nspasteboard.ConcealedType",
                        "org.nspasteboard.TransientType",
                    ]
                ),
                (
                    "Apple Passwords/Keychain",
                    [
                        "public.utf8-plain-text", "org.nspasteboard.ConcealedType",
                        "org.nspasteboard.AutoGeneratedType",
                    ]
                ),
            ] as [(String, Set<String>)])
        func passwordManagerCopiesVetoed(manager: String, types: Set<String>) async {
            let pasteboard = FakePasteboard()
            let monitor = makeMonitor(pasteboard: pasteboard)
            var captures: [PasteboardCapture] = []
            var ignores: [CaptureIgnoreReason] = []
            monitor.onCapture = { captures.append($0) }
            monitor.onIgnore = { ignores.append($0) }

            pasteboard.write(.text("hunter2"), types: types)
            monitor.pollOnce()
            try? await Task.sleep(for: .milliseconds(80))

            #expect(captures.isEmpty, "\(manager) copy must never be stored")
            #expect(pasteboard.readCalls == 0, "veto must run before the read")
            #expect(ignores == [.sensitiveType])
        }

        @Test("Denylisted source app is vetoed before any read")
        func denylistVeto() async {
            let pasteboard = FakePasteboard()
            var denylist = SourceAppDenylist()
            denylist.add("com.example.banking")
            let monitor = makeMonitor(
                pasteboard: pasteboard, denylist: denylist, frontmost: "com.example.banking")
            var captures: [PasteboardCapture] = []
            var ignores: [CaptureIgnoreReason] = []
            monitor.onCapture = { captures.append($0) }
            monitor.onIgnore = { ignores.append($0) }

            pasteboard.write(.text("account number"), types: ["public.utf8-plain-text"])
            monitor.pollOnce()
            try? await Task.sleep(for: .milliseconds(80))

            #expect(captures.isEmpty)
            #expect(pasteboard.readCalls == 0)
            #expect(ignores == [.denylistedApp])
        }

        @Test("Suggested denylist covers the major password managers by default")
        func suggestedListPreloaded() {
            let denylist = SourceAppDenylist()
            #expect(denylist.contains("com.1password.1password"))
            #expect(denylist.contains("com.bitwarden.desktop"))
            #expect(denylist.contains("com.apple.Passwords"))
            #expect(!denylist.contains("com.apple.Safari"))
        }

        @Test("User can re-enable a suggested app, and re-block it")
        func suggestionOverrides() {
            var denylist = SourceAppDenylist()
            denylist.remove("com.bitwarden.desktop")
            #expect(!denylist.contains("com.bitwarden.desktop"))
            denylist.add("com.bitwarden.desktop")
            #expect(denylist.contains("com.bitwarden.desktop"))
        }

        @Test("Manual denylist entries are trimmed before storage and matching")
        func manualEntryTrimming() {
            var denylist = SourceAppDenylist()
            denylist.add("  com.example.banking\n")
            denylist.add(" \n ")

            #expect(denylist.userBundleIDs == ["com.example.banking"])
            #expect(denylist.contains("com.example.banking"))
            #expect(denylist.contains("\ncom.example.banking "))
        }

        @Test("Denylist persists through UserDefaults")
        func denylistRoundTrip() throws {
            let suite = "denylist-test-\(UUID().uuidString)"
            let defaults = try #require(UserDefaults(suiteName: suite))
            defer { defaults.removePersistentDomain(forName: suite) }

            var denylist = SourceAppDenylist()
            denylist.add("com.example.bank")
            denylist.remove("com.apple.Passwords")
            denylist.save(to: defaults)

            #expect(SourceAppDenylist.load(from: defaults) == denylist)
        }

        @Test("Ignore-next-copy skips exactly one change, before reading")
        func ignoreNextCopy() async {
            let pasteboard = FakePasteboard()
            let monitor = makeMonitor(pasteboard: pasteboard)
            var captures: [PasteboardCapture] = []
            var ignores: [CaptureIgnoreReason] = []
            monitor.onCapture = { captures.append($0) }
            monitor.onIgnore = { ignores.append($0) }

            monitor.ignoreNextCopy()
            pasteboard.write(.text("skip me"), types: ["public.utf8-plain-text"])
            monitor.pollOnce()
            try? await Task.sleep(for: .milliseconds(80))
            #expect(captures.isEmpty)
            #expect(pasteboard.readCalls == 0)

            pasteboard.write(.text("capture me"), types: ["public.utf8-plain-text"])
            monitor.pollOnce()
            for _ in 0..<200 where captures.isEmpty {
                try? await Task.sleep(for: .milliseconds(5))
            }
            #expect(captures.map(\.textRepresentation) == ["capture me"])
            #expect(ignores == [.userIgnoredNext])
        }

        @Test("Ignored events carry reason and time — never content")
        func recorderCountsWithoutContent() {
            let recorder = InMemoryPrivacyEventRecorder()
            let weekAgo = Date(timeIntervalSinceNow: -7 * 86_400)

            recorder.record(IgnoredCaptureEvent(reason: .sensitiveType))
            recorder.record(IgnoredCaptureEvent(reason: .denylistedApp))
            recorder.record(
                IgnoredCaptureEvent(
                    reason: .userIgnoredNext,
                    occurredAt: Date(timeIntervalSinceNow: -30 * 86_400)))

            #expect(recorder.eventCount(since: weekAgo) == 2)
            // The event type has no payload field at all; assert the codable
            // surface stays that way (reason + occurredAt only).
            let event = IgnoredCaptureEvent(reason: .sensitiveType)
            let json = try? JSONEncoder().encode(event)
            let keys =
                (try? JSONSerialization.jsonObject(with: json ?? Data()) as? [String: Any])?
                .keys.sorted() ?? []
            #expect(keys == ["occurredAt", "reason"])
        }
    }
#endif
