#if os(macOS)
    import Foundation
    import Testing

    @testable import ClipboardCore

    @MainActor
    private func makeMonitor(
        pasteboard: FakePasteboard,
        denylist: SourceAppDenylist = SourceAppDenylist(),
        frontmost: String? = nil
    ) -> MacPasteboardMonitor {
        let monitor = MacPasteboardMonitor(
            reader: pasteboard, activity: FakeActivity(),
            frontmostApp: { frontmost })
        monitor.denylist = denylist
        return monitor
    }

    @Suite("Sensitive-content guardrails")
    @MainActor
    struct SensitiveContentTests {

        /// The exact pasteboard shapes the big password managers write:
        /// all of them carry `org.nspasteboard.ConcealedType` (the
        /// nspasteboard.org convention they implement).
        @Test(
            "Password-manager copies are never stored",
            arguments: [
                ("1Password", ["public.utf8-plain-text", "org.nspasteboard.ConcealedType"]),
                (
                    "Bitwarden",
                    [
                        "public.utf8-plain-text", "org.nspasteboard.ConcealedType",
                        "org.nspasteboard.TransientType"
                    ]
                ),
                (
                    "Apple Passwords/Keychain",
                    [
                        "public.utf8-plain-text", "org.nspasteboard.ConcealedType",
                        "org.nspasteboard.AutoGeneratedType"
                    ]
                )
            ] as [(String, Set<String>)])
        func passwordManagerCopiesVetoed(manager: String, types: Set<String>) async {
            let pasteboard = FakePasteboard()
            let monitor = makeMonitor(pasteboard: pasteboard)
            var captures: [PasteboardCapture] = []
            var ignores: [CaptureIgnoreReason] = []
            monitor.onCapture = { captures.append($0) }
            monitor.onIgnore = { ignores.append($0) }

            pasteboard.write(.text("hunter2"), types: types)
            monitor.pollOnce()
            try? await Task.sleep(for: .milliseconds(80))

            #expect(captures.isEmpty, "\(manager) copy must never be stored")
            #expect(pasteboard.readCalls == 0, "veto must run before the read")
            #expect(ignores == [.sensitiveType])
        }

        @Test("Denylisted source app is vetoed before any read")
        func denylistVeto() async {
            let pasteboard = FakePasteboard()
            var denylist = SourceAppDenylist()
            denylist.add("com.example.banking")
            let monitor = makeMonitor(
                pasteboard: pasteboard, denylist: denylist, frontmost: "com.example.banking")
            var captures: [PasteboardCapture] = []
            var ignores: [CaptureIgnoreReason] = []
            monitor.onCapture = { captures.append($0) }
            monitor.onIgnore = { ignores.append($0) }

            pasteboard.write(.text("account number"), types: ["public.utf8-plain-text"])
            monitor.pollOnce()
            try? await Task.sleep(for: .milliseconds(80))

            #expect(captures.isEmpty)
            #expect(pasteboard.readCalls == 0)
            #expect(ignores == [.denylistedApp])
        }

        @Test("Suggested denylist covers the major password managers by default")
        func suggestedListPreloaded() {
            let denylist = SourceAppDenylist()
            #expect(denylist.contains("com.1password.1password"))
            #expect(denylist.contains("com.bitwarden.desktop"))
            #expect(denylist.contains("com.apple.Passwords"))
            #expect(denylist.contains("com.markmcguill.strongbox.mac"))
            #expect(denylist.contains("com.keepassium.ios"))
            #expect(!denylist.contains("com.apple.Safari"))
        }

        @Test("User can re-enable a suggested app, and re-block it")
        func suggestionOverrides() {
            var denylist = SourceAppDenylist()
            denylist.remove("com.bitwarden.desktop")
            #expect(!denylist.contains("com.bitwarden.desktop"))
            denylist.add("com.bitwarden.desktop")
            #expect(denylist.contains("com.bitwarden.desktop"))
        }

        @Test("Restoring suggestions re-blocks every allowed one, keeps user entries")
        func restoreSuggestions() {
            var denylist = SourceAppDenylist()
            denylist.remove("com.bitwarden.desktop")
            denylist.remove("com.apple.Passwords")
            denylist.add("com.example.banking")

            denylist.restoreSuggestions()

            #expect(denylist.contains("com.bitwarden.desktop"))
            #expect(denylist.contains("com.apple.Passwords"))
            #expect(denylist.contains("com.example.banking"), "user entries survive the restore")
            #expect(denylist.disabledSuggestions.isEmpty)
        }

        @Test("Built-in suggestions carry a name and a category, and the set matches")
        func suggestionsAreDescribed() {
            let ids = SourceAppDenylist.suggestions.map(\.id)
            #expect(Set(ids) == SourceAppDenylist.suggestedBundleIDs)
            #expect(ids.count == Set(ids).count, "no duplicate bundle ids")
            #expect(SourceAppDenylist.suggestions.allSatisfy { !$0.name.isEmpty })
            for category in SourceAppDenylist.SuggestionCategory.allCases {
                #expect(
                    SourceAppDenylist.suggestions.contains { $0.category == category },
                    "every category lists at least one app")
            }
        }

        @Test(
            "Bundle identifier plausibility: reverse-DNS shape, nothing else",
            arguments: [
                ("com.apple.Safari", true),
                ("  com.example.banking\n", true),
                ("com.enpass.Enpass-Desktop", true),
                ("org.keepassxc.keepassxc", true),
                ("a.b", true),
                ("safari", false),
                ("", false),
                ("   ", false),
                ("com.", false),
                (".apple", false),
                ("com..apple", false),
                ("com.apple.Safari app", false),
                ("com/apple", false),
                ("com.apple.sáfari", false)
            ])
        func bundleIdentifierPlausibility(candidate: String, expected: Bool) {
            #expect(SourceAppDenylist.isPlausibleBundleIdentifier(candidate) == expected)
        }

        @Test("Adding a built-in app switches it back on instead of listing it twice")
        func addingABuiltInKeepsOneEntry() {
            var denylist = SourceAppDenylist()
            denylist.setSuggestion("com.apple.Passwords", active: false)
            #expect(!denylist.contains("com.apple.Passwords"))

            denylist.add("com.apple.Passwords")

            #expect(denylist.contains("com.apple.Passwords"))
            #expect(denylist.isSuggestionActive("com.apple.Passwords"))
            #expect(
                denylist.userBundleIDs.isEmpty,
                "a built-in app never becomes a removable user entry")
        }

        @Test(
            "No built-in app ever lands in the user entries, however it is added",
            arguments: SourceAppDenylist.suggestions.map(\.id))
        func builtInsStayOutOfUserEntries(bundleID: String) {
            var added = SourceAppDenylist()
            added.setSuggestion(bundleID, active: false)
            added.add(" \(bundleID)\n")
            #expect(added.userBundleIDs.isEmpty, "the Settings user rows never list a built-in app")
            #expect(added.contains(bundleID))

            let constructed = SourceAppDenylist(userBundleIDs: [bundleID, "com.example.banking"])
            #expect(constructed.userBundleIDs == ["com.example.banking"])
            #expect(constructed.contains(bundleID))
        }

        @Test("The built-in switch drives one app, leaves user entries alone, and restores")
        func suggestionSwitch() {
            var denylist = SourceAppDenylist()
            denylist.add("com.example.banking")

            denylist.setSuggestion("com.bitwarden.desktop", active: false)
            #expect(!denylist.isSuggestionActive("com.bitwarden.desktop"))
            #expect(!denylist.contains("com.bitwarden.desktop"))
            #expect(denylist.contains("com.example.banking"))

            denylist.setSuggestion("com.bitwarden.desktop", active: true)
            #expect(denylist.contains("com.bitwarden.desktop"))

            denylist.setSuggestion("com.example.banking", active: false)
            #expect(
                denylist.contains("com.example.banking"), "the switch only drives built-in apps")
            #expect(!denylist.isSuggestionActive("com.example.banking"))

            denylist.setSuggestion("com.apple.Passwords", active: false)
            denylist.restoreSuggestions()
            #expect(denylist.isSuggestionActive("com.apple.Passwords"))
            #expect(denylist.userBundleIDs == ["com.example.banking"])
        }

        @Test(
            "A list saved with built-in apps as user entries loads folded, protecting the same apps",
            arguments: [false, true])
        func legacyOverlapLoadsFolded(builtInWasSwitchedOff: Bool) throws {
            let disabled =
                builtInWasSwitchedOff
                ? #"["com.apple.Passwords","com.bitwarden.desktop"]"#
                : #"["com.bitwarden.desktop"]"#
            let legacy =
                #"{"userBundleIDs":["com.apple.Passwords","com.example.banking"],"disabledSuggestions":\#(disabled)}"#

            let loaded = try JSONDecoder().decode(SourceAppDenylist.self, from: Data(legacy.utf8))

            #expect(loaded.userBundleIDs == ["com.example.banking"])
            #expect(
                loaded.contains("com.apple.Passwords"), "the user's explicit add still protects it")
            #expect(loaded.isSuggestionActive("com.apple.Passwords"))
            #expect(!loaded.contains("com.bitwarden.desktop"), "an unrelated switch-off survives")
            #expect(loaded.contains("com.example.banking"))

            let suite = "denylist-legacy-\(UUID().uuidString)"
            let defaults = try #require(UserDefaults(suiteName: suite))
            defer { defaults.removePersistentDomain(forName: suite) }
            loaded.save(to: defaults)
            #expect(SourceAppDenylist.load(from: defaults) == loaded)
        }

        @Test("Manual denylist entries are trimmed before storage and matching")
        func manualEntryTrimming() {
            var denylist = SourceAppDenylist()
            denylist.add("  com.example.banking\n")
            denylist.add(" \n ")

            #expect(denylist.userBundleIDs == ["com.example.banking"])
            #expect(denylist.contains("com.example.banking"))
            #expect(denylist.contains("\ncom.example.banking "))
        }

        @Test("Denylist persists through UserDefaults")
        func denylistRoundTrip() throws {
            let suite = "denylist-test-\(UUID().uuidString)"
            let defaults = try #require(UserDefaults(suiteName: suite))
            defer { defaults.removePersistentDomain(forName: suite) }

            var denylist = SourceAppDenylist()
            denylist.add("com.example.bank")
            denylist.remove("com.apple.Passwords")
            denylist.save(to: defaults)

            #expect(SourceAppDenylist.load(from: defaults) == denylist)
        }

        @Test("Ignore-next-copy skips exactly one change, before reading")
        func ignoreNextCopy() async {
            let pasteboard = FakePasteboard()
            let monitor = makeMonitor(pasteboard: pasteboard)
            var captures: [PasteboardCapture] = []
            var ignores: [CaptureIgnoreReason] = []
            monitor.onCapture = { captures.append($0) }
            monitor.onIgnore = { ignores.append($0) }

            monitor.ignoreNextCopy()
            pasteboard.write(.text("skip me"), types: ["public.utf8-plain-text"])
            monitor.pollOnce()
            try? await Task.sleep(for: .milliseconds(80))
            #expect(captures.isEmpty)
            #expect(pasteboard.readCalls == 0)

            pasteboard.write(.text("capture me"), types: ["public.utf8-plain-text"])
            monitor.pollOnce()
            for _ in 0..<200 where captures.isEmpty {
                try? await Task.sleep(for: .milliseconds(5))
            }
            #expect(captures.map(\.textRepresentation) == ["capture me"])
            #expect(ignores == [.userIgnoredNext])
        }

        @Test("Ignored events carry reason and time — never content")
        func recorderCountsWithoutContent() {
            let recorder = InMemoryPrivacyEventRecorder()
            let weekAgo = Date(timeIntervalSinceNow: -7 * 86_400)

            recorder.record(IgnoredCaptureEvent(reason: .sensitiveType))
            recorder.record(IgnoredCaptureEvent(reason: .denylistedApp))
            recorder.record(
                IgnoredCaptureEvent(
                    reason: .userIgnoredNext,
                    occurredAt: Date(timeIntervalSinceNow: -30 * 86_400)))

            #expect(recorder.eventCount(since: weekAgo) == 2)
            // The event type has no payload field at all; assert the codable
            // surface stays that way (reason + occurredAt only).
            let event = IgnoredCaptureEvent(reason: .sensitiveType)
            let json = try? JSONEncoder().encode(event)
            let keys =
                (try? JSONSerialization.jsonObject(with: json ?? Data()) as? [String: Any])?
                .keys.sorted() ?? []
            #expect(keys == ["occurredAt", "reason"])
        }
    }
#endif
