import Foundation

/// Why a pasteboard change was NOT captured. Carries no content by
/// construction — the Privacy Center counts these ("X items ignored this
/// week") without ever having seen what was ignored.
public enum CaptureIgnoreReason: String, Sendable, Codable, CaseIterable {
    /// `org.nspasteboard` Concealed/Transient/AutoGenerated marker.
    case sensitiveType
    /// The source app is on the denylist.
    case denylistedApp
    /// The user armed "ignore next copy".
    case userIgnoredNext
    /// Capture preferences exclude this payload kind.
    case preferenceFiltered
}

/// One ignored-capture event: reason + timestamp, nothing else.
public struct IgnoredCaptureEvent: Sendable, Equatable, Codable {
    public var reason: CaptureIgnoreReason
    public var occurredAt: Date

    public init(reason: CaptureIgnoreReason, occurredAt: Date = .now) {
        self.reason = reason
        self.occurredAt = occurredAt
    }
}

/// Sink for ignored-capture events. The GRDB store provides the durable
/// implementation once persistence lands; until then the in-memory recorder
/// keeps the wiring honest and testable.
public protocol PrivacyEventRecording: Sendable {
    func record(_ event: IgnoredCaptureEvent)
    func eventCount(since date: Date) -> Int
}

/// Thread-safe in-memory recorder (also the test double).
public final class InMemoryPrivacyEventRecorder: PrivacyEventRecording, @unchecked Sendable {
    private let lock = NSLock()
    private var events: [IgnoredCaptureEvent] = []

    public init() {}

    public func record(_ event: IgnoredCaptureEvent) {
        lock.withLock { events.append(event) }
    }

    public func eventCount(since date: Date) -> Int {
        lock.withLock { events.count(where: { $0.occurredAt >= date }) }
    }

    /// Per-reason breakdown for the Privacy Center ("why was it ignored").
    public func countsByReason(since date: Date) -> [CaptureIgnoreReason: Int] {
        lock.withLock {
            events.filter { $0.occurredAt >= date }
                .reduce(into: [:]) { counts, event in counts[event.reason, default: 0] += 1 }
        }
    }

    /// Test hook: every recorded event, oldest first.
    public func allEvents() -> [IgnoredCaptureEvent] {
        lock.withLock { events }
    }
}
