import Foundation
import GanchoKit
import Synchronization

/// Why a pasteboard change was NOT captured. Carries no content by
/// construction — the Privacy Center counts these ("X items ignored this
/// week") without ever having seen what was ignored.
public enum CaptureIgnoreReason: String, Sendable, Codable, CaseIterable {
    /// `org.nspasteboard` Concealed/Transient/AutoGenerated marker.
    case sensitiveType
    /// The source app is on the denylist.
    case denylistedApp
    /// The user armed "ignore next copy".
    case userIgnoredNext
    /// Capture preferences exclude this payload kind.
    case preferenceFiltered
}

/// One ignored-capture event: reason + timestamp, nothing else.
public struct IgnoredCaptureEvent: Sendable, Equatable, Codable {
    public var reason: CaptureIgnoreReason
    public var occurredAt: Date

    public init(reason: CaptureIgnoreReason, occurredAt: Date = .now) {
        self.reason = reason
        self.occurredAt = occurredAt
    }
}

/// A sync milestone for the Privacy Center log — metadata only (what kind of
/// activity and how many items), never the clip content.
public enum SyncActivityKind: String, Sendable, Codable, CaseIterable {
    case synced
    case paused
    case failed
}

/// One sync log entry: kind + an optional readable cause + timestamp. No
/// clip content, ever — this is what the Privacy Center shows.
public struct SyncActivityEvent: Sendable, Equatable, Codable {
    public var kind: SyncActivityKind
    /// Structured cause for paused/failed (the UI localizes it); nil when clean.
    public var cause: SyncInterruption?
    public var occurredAt: Date

    public init(kind: SyncActivityKind, cause: SyncInterruption? = nil, occurredAt: Date = .now) {
        self.kind = kind
        self.cause = cause
        self.occurredAt = occurredAt
    }
}

/// Sink for ignored-capture events. The GRDB store provides the durable
/// implementation once persistence lands; until then the in-memory recorder
/// keeps the wiring honest and testable.
public protocol PrivacyEventRecording: Sendable {
    func record(_ event: IgnoredCaptureEvent)
    func eventCount(since date: Date) -> Int
    /// Records a sync milestone (metadata only) for the Privacy Center log.
    func record(sync event: SyncActivityEvent)
    /// Most recent sync milestones, newest first.
    func recentSyncEvents(limit: Int) -> [SyncActivityEvent]
}

/// Thread-safe in-memory recorder (also the test double).
public final class InMemoryPrivacyEventRecorder: PrivacyEventRecording {
    private struct State: Sendable {
        var events: [IgnoredCaptureEvent] = []
        var syncEvents: [SyncActivityEvent] = []
    }

    private let state = Mutex(State())

    public init() {}

    public func record(_ event: IgnoredCaptureEvent) {
        state.withLock { $0.events.append(event) }
    }

    public func record(sync event: SyncActivityEvent) {
        state.withLock { $0.syncEvents.append(event) }
    }

    public func recentSyncEvents(limit: Int) -> [SyncActivityEvent] {
        state.withLock { Array($0.syncEvents.suffix(limit).reversed()) }
    }

    public func eventCount(since date: Date) -> Int {
        state.withLock { $0.events.count(where: { $0.occurredAt >= date }) }
    }

    /// Per-reason breakdown for the Privacy Center ("why was it ignored").
    public func countsByReason(since date: Date) -> [CaptureIgnoreReason: Int] {
        state.withLock { state in
            state.events.filter { $0.occurredAt >= date }
                .reduce(into: [:]) { counts, event in counts[event.reason, default: 0] += 1 }
        }
    }

    /// Test hook: every recorded event, oldest first.
    public func allEvents() -> [IgnoredCaptureEvent] {
        state.withLock { $0.events }
    }
}
