import Foundation

/// Pasteboard markers that must NEVER be captured.
/// Password managers (1Password, Bitwarden, Apple Passwords) and well-behaved
/// apps tag their writes with these; see nspasteboard.org for the convention.
public enum SensitivePasteboardTypes {
    /// Content that should not be stored (passwords, one-time codes).
    public static let concealed = "org.nspasteboard.ConcealedType"
    /// Ephemeral content not meant for history (e.g. drag-and-drop shims).
    public static let transient = "org.nspasteboard.TransientType"
    /// Programmatically generated content (not a user copy).
    public static let autoGenerated = "org.nspasteboard.AutoGeneratedType"
    /// Items arriving via Universal Clipboard / Handoff (capture with a badge;
    /// sync must never duplicate them against already-synced items).
    public static let remoteClipboard = "com.apple.is-remote-clipboard"

    /// Types whose presence vetoes capture entirely.
    public static let captureVeto: Set<String> = [concealed, transient, autoGenerated]
}
